### PR TITLE
Update rules namespaces

### PR DESCRIPTION
**Pull request by samfrench**
* Updates namespaces
* Updates target ruby version
* Updates installed gems as GitHub showed a security vulnerability

### CODE REVIEW

**Review by ettomatic — APPROVED** [review]
Looks good to me!

**Review by woodyblah — APPROVED** [review]
EDIT: see below. I can't seem to delete my approval 😆

**Review by woodyblah — CHANGES_REQUESTED** [review]
This causes `# frozen_string_literal: true` to appear at the top of almost every file :/

**Review by woodyblah — APPROVED** [review]
I've now learned what the frozen string literal is for 👍

**Pull request merged**
